### ISSUE TITLE
How to upload files?

### ISSUE THREAD

**Issue by xvilo** [RocketChat/Rocket.Chat.js.SDK#22]
Is it possible to upload files through the SDK? Couldn't find any related methods

**Comment by timkinnane** [comment]
Hi @xvilo - You can use the SDK to send custom message objects via `driver.sendMessage()` ([see the Message interface](https://github.com/RocketChat/Rocket.Chat.js.SDK/blob/master/src/config/messageInterfaces.ts)).

So you can add URL for attachments, but to actually "upload" like a user dragging a file into the client, would require the server the SDK is running on to host and stream a file to the server. That's theoretically possible but not a common use case so I don't think we'll provide helpers. You could still use the SDK and `driver.asyncCall()` to make a custom server method call if you can figure out the streaming requirements.

**Comment by djlazz3** [comment]
just a note, i was able to get that "upload" functionality with just `driver.sendMessage()` like so...

```
return driver.sendMessage({
  msg: "Message goes here",
  rid: 'RoomId goes here',
  attachments: [{
    fields: [{
      value: "File to upload"
    }],
    text: "File description goes here"
  }]
})
```
this helped me figure this out:
https://github.com/RocketChat/Rocket.Chat.js.SDK/blob/e507e86faf049751218a08f6488545ec77d33309/src/config/messageInterfaces.ts#L3

**Comment by solanha1999** [comment]
> just a note, i was able to get that "upload" functionality with just `driver.sendMessage()` like so...
> 
> ```
> return driver.sendMessage({
>   msg: "Message goes here",
>   rid: 'RoomId goes here',
>   attachments: [{
>     fields: [{
>       value: "File to upload"
>     }],
>     text: "File description goes here"
>   }]
> })
> ```
> 
> this helped me figure this out:
> https://github.com/RocketChat/Rocket.Chat.js.SDK/blob/e507e86faf049751218a08f6488545ec77d33309/src/config/messageInterfaces.ts#L3

Hi @djlazz3 I wanna know how a get the file to upload I tryed to put the directory path to file, but it didn't work, it sent its own string path. Could you help me please?

**Comment by felipetomm** [comment]
@solanha1999 , you could make the upload with [api/v1/rooms.upload/:rid](https://developer.rocket.chat/api/rest-api/endpoints/rooms/upload). In the same request, you can send an message, or, after this, you have the path of file hosted on server, and you can send an message separately.

The attachments prop is only an path to an file. The path of the file can be a external and acessible link or an "internal" file on server.

**Comment by solanha1999** [comment]
@felipetomm Thanks thats great, but i dont know how do i do that (https://developer.rocket.chat/api/rest-api/endpoints/rooms/upload#example-call) in nodeJS i use the curl conversor (https://onlinedevtools.in/curl), but it don't work. 
Do u know what i can do?
I thank you in advance!

**Comment by felipetomm** [comment]
@solanha1999, the code converter result that's incomplete, in node you need to use something like a form-data. Can you see more [here](https://stackoverflow.com/questions/40131060/node-js-multipart-form-data-local-file-upload-to-api), has an example of upload local file to an POST API using form-data. I use this method and is functionally.
I hope that you get it :)

**Comment by solanha1999** [comment]
Sorry @felipetomm, but It's not working for me here's my code:
![image](https://user-images.githubusercontent.com/86743159/125349291-be459300-e333-11eb-8157-673cd6aacf91.png)
do u know what I'm doing wrong?

**Comment by felipetomm** [comment]
In my case i use axios to make a post. 
I think that you need to specify form-data in headers, something like this:
```js
const FormData = require('form-data');
let form = new FormData();

form.append('file', fs.createReadStream('PATH_OF_FILE'), 'NameOfFile.pdf');
const config = {
    headers: {
        'Content-Type': 'multipart/form-data; boundary=' + form.getBoundary(),
        'X-Auth-Token': authToken,
        'X-User-Id': userId
    }
}
await axios.post(`${ROCKET_CHAT_HOST}/api/v1/rooms.upload/${roomId}`, form, config);
```
Try this, and if is possible, post the status code or result from your try

**Comment by solanha1999** [comment]
@felipetomm thanks, my code works very well, i just have to add the Room or User ID to work, so now i trying to get the User and Room ID by the function getDirectMessageRoomId and getRoomId, that returns a [object Promise]

**Comment by felipetomm** [comment]
if return a **[object Promise]**, use **await** before call method:
```js
// you have
driver.getDirectMessageRoomId('something_here')

// you need
await driver.getDirectMessageRoomId('something_here')

// or then
driver.getDirectMessageRoomId('something_here')
 .then((result) => {
     // do something
})

**Comment by solanha1999** [comment]
Thank you!!!! That's work very well!!!
