### ISSUE TITLE
driver.js - ignoring edited messages results in an error

### ISSUE THREAD

**Issue by nsdev0** [RocketChat/Rocket.Chat.js.SDK#27]
dist/lib/driver.js:397

When checking whether the message was edited or not, it gives an error: '`TypeError: Cannot read property '$date' of null`'.
Occurs because of what typeof message.editedAt is 'object' even if the message was not edited.

> npm v6.4.0
> nodejs v10.8.0
> botkit-starter-rocketchat v0.0.17

**Comment by timkinnane** [comment]
@nsdev0 That's very odd. There's a condition to see if `editedAt` is **undefined** but I've never seen it come through as **null**.

I've just pushed a fix for the edited message logic that should catch either. Saw your commit on the fork after, but I think it's better to make a loose check on `editedAt` being truthy, to catch undefined or null. Also added tests. Check out [0.2.5](https://www.npmjs.com/package/@rocket.chat/sdk).
