### ISSUE TITLE
Will proxy usage be implemented?

### ISSUE THREAD

**Issue by GiverOfGifts** [RocketChat/Rocket.Chat.js.SDK#36]
I've been trying to use this sdk's api with a proxy but was unable to find an option to do so. 
It would be nice if I could set a proxy with environment variables (http_proxy / https_proxy) but I don't think node-rest-client supports this.

Are there any plans to implement proxy usage?

**Comment by timkinnane** [comment]
@GiverOfGifts Node rest client is only used for the API helpers in the SDK. How are you using it? It's most commonly a component of Rocket.Chat bot adapters, so it's interesting to hear different implementations and will help to answer your question.

There's currently some PRs that need to be merged which includes replacing node-rest-client with [Axios](https://github.com/axios/axios). Would that help? Not sure I can give you a timeline on it though.

**Comment by GiverOfGifts** [comment]
@timkinnane I want to synchronize user information from a central database with RocketChat regularly. The database is in a private network. In its current setup I can only run a VM inside this network to grab user data, then update RocketChat over a proxy.

The PRs that replace nrc with Axios should work: https://github.com/axios/axios/blob/master/README.md#request-config

> // You can also define your proxy using the conventional `http_proxy` and
  // `https_proxy` environment variables.
