### ISSUE TITLE
Upgrade to Asteroid v2 or find a better maintained DDP client

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat.js.SDK#4]
Asteroid v2 provides two improvements over v1; more consistent use of async methods and a more useful connection object. Specifically, connections can actually be cancelled / disconnected.

The problem is, they dropped their internal DDP methods in favour of a mixin model. The DDP mixin they provide as an external module now has a different interface and I couldn't get it working with our existing `reactiveQuery` methods.

In any case, Asteroid v2 doesn't seem to be maintained anymore either, so even though it's marginally better than v1, perhaps we should look for an actively maintained package if we need to refactor anyway.

**Comment by abhishek71994** [comment]
Is this issue taken up by you @JoseRenan ?

**Comment by JoseRenan** [comment]
Yes  :+1:
