### ISSUE TITLE
Can't install the alpha version

### ISSUE THREAD

**Issue by uncledent** [RocketChat/Rocket.Chat.js.SDK#58]
I get the following error in the bundler: 

bundling failed: Error: Unable to resolve module `paho-mqtt/src/paho-mqtt` from `.../node_modules/@rocket.chat/sdk/lib/drivers/mqtt.js`: Module `paho-mqtt/src/paho-mqtt` does not exist in the Haste module map

React native

**Comment by diegolmello** [comment]
@uncledent Try again using yarn.

**Comment by uncledent** [comment]
@diegolmello  thank you, it worked
