### ISSUE TITLE
sdk.conect() - unhandled promise rejection when offline on react native

### ISSUE THREAD

**Issue by uncledent** [RocketChat/Rocket.Chat.js.SDK#59]
```
    this.sdk
      .connect()
      .then(async () => {
        Logger.log('sdk connect success');
      })
      .catch(err => {
        log('sdk connect failure', err);
      });
```

This does work, when app is online, but if you start it offline, then there is an uncaught promise rejection, which can not be caught.

Any idea?

**Comment by uncledent** [comment]
Sorry, my fault. It is OK. Thank you!

**Comment by diegolmello** [comment]
@uncledent Have you checked our [React Native client](https://github.com/RocketChat/Rocket.Chat.ReactNative)?

It uses this SDK already: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/rocketchat.js#L170

**Comment by uncledent** [comment]
@diegolmello yes, thank you! We are doing own one as part of the product :)

**Comment by diegolmello** [comment]
@uncledent Nice! Make sure to join #react-native channel at open server in order to receive updates.
