### ISSUE TITLE
Add missing env variables from adapter

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat.js.SDK#7]
While writing developer docs I noticed that the Hubot Adapter implements a few environment variables that aren't used in the SDK. Namely:
- `ROCKETCHAT_USER`
- `ROCKETCHAT_PASSWORD`
- `ROCKETCHAT_ROOM`
- `ROCKETCHAT_USESSL`

These should all be carried over to the SDK so bots in other frameworks can set them in a consistent way. Ideally, the only additional environment variables required in the adapter should be for behaviour specific to that framework.

**Comment by arthurTemporim** [comment]
In dist/utils/config.js:

// The Bot user, will attempt to login and run methods in tests
exports.botUser = {
    email: 'bot@localhost',
    name: 'Bot',
    password: process.env.ROCKETCHAT_PASSWORD || 'pass',
    username: process.env.ROCKETCHAT_USER || 'bot',
    active: true,
    roles: ['bot'],
    joinDefaultChannels: true,
    requirePasswordChange: false,
    sendWelcomeEmail: false,
    verified: true
};

This code solve this issue about ROCKETCHAT_USER and ROCKETCHAT_PASSWORD?

**Comment by timkinnane** [comment]
No the `utils` methods are only used in tests. Don't worry about it though, I've actually got a fix I'm about to push.
