### ISSUE TITLE
Asteroid connection timeout

### ISSUE THREAD

**Issue by galr52** [RocketChat/Rocket.Chat.js.SDK#71]
rocketchat version: 0.48
SDK version 0.2.9-2

i am trying to connect using the sdk but getting connection timeout

my code: 
`const { driver } = require('@rocket.chat/sdk');

const conn = await driver.connect( { host: 'rocket.chat', useSsl: true})
`

error:
[connect] Timeout (20000)
Error: Asteroid connection timeout

EDIT:

the problem was with windows 7, when i tried in ubuntu it worked perfect

**Comment by time4Wiley** [comment]
I met the same.

connecting to Server running on macOS.

Has it ever been fixed?

**Comment by MrPoint1400** [comment]
+1

**Comment by MrPoint1400** [comment]
rocketchat version: 6.2.2
SDK version latest
node 14 
node 18
windows 10

i am trying to connect using the sdk but getting connection timeout

my code:
`const { driver } = require('@rocket.chat/sdk');

const conn = await driver.connect( { host: 'https://rocketchat.myhost.com', useSsl: true})
`

error:
[connect] Timeout (20000)
Error: Asteroid connection timeout
