### ISSUE TITLE
Livechat: Confusion over bots, agents and departments

### ISSUE THREAD

**Issue by MrEscaGreenwing** [RocketChat/Rocket.Chat.js.SDK#80]
Hi, 
I'm trying to write my own adapter that logs in as a bot user (livechat agent) and handles the requests of guests. The bot is part of a _BOT_ department. Furthermore I have a service worker account (also livechat agent) in a _SERVICE_ department that shall take over the chat/room as soon as the bot can't help the visitor.

Until yesterday my bot was able to manage multiple requests of different guests. But without any changes the behavior suddenly changed. Not possible - i know.

At first every in the livechat registered visitor who opened a new room got automatically handled by the bot - regardless which department I had selected and if the service worker is online, too. Since yesterday I need to define the correct department (_BOT_) when a visitor opens a room to get handled by the bot. But as soon as the bot handles one visitor, the next visitor automatically needs to get handled by the service worker if he's online (obviously round robin rule) although the requested department is still _BOT_. Now I'm completely confused... Is the department relevant or not? When and how does the bot handles the room?

The behavior I want to implement is the following: Bot and service worker both are logged in. If a new visitor opens a room he always gets handled by the bot. Only if the bot transfers the room, the service worker needs to act. Can someone tell me what's the correct way to accomplish this? And maybe even know what could be the reason of the changed behavior although no code was changed? (Maybe settings on the Rocket.Chat server?)

Thank you in advance!

FYI: I'm using alpha version 26 of the SDK.

**Comment by krishnaprasadhg** [comment]
Hello,

Could you please help with api for transferring bot session to live chat agent?
i'm calling room.forward (Sample one is below). but session not transferring to live agent.

curl -H "X-Auth-Token: 9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq" \
     -H "X-User-Id: aobEdbYhXfu5hkeqG" \
     -H "Content-type: application/json" \
     http://localhost:3000/api/v1/livechat/room.forward \
     -d '{"roomId": "XFzMqgn33DcsQkpJp", "departmentId": "wXpPLofkffqWAwDNF"}'


Getting error

{ status: 'error',
  message: 'You must be logged in to do this.' }

**Comment by MrEscaGreenwing** [comment]
An update to version 1.0.3 of the Rocket.Chat-Server seems to have fixed this error. That's why I'm closing the issue.
